version: '3.8'
services:
  django:
    image: django_test:latest 
    ports:
      - 8000:8000
    deploy:
      replicas: 2
    networks:
      - webnet

  react:
    image: react:latest
    ports:
      - 3000:3000
    networks:
      - webnet

  llm_service:
    image: llm:latest
    ports:
      - 5000:5000
    networks:
      - webnet

  flutter:
    image: flutter-app:latest
    ports:
      - 9000:80
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
